<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ressourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

      public $totalRows ;

      public function findAllPaginated($limit, $page, array $sorting = array()){
          $fields = array_keys($this->getClassMetadata()->fieldMappings);
          $qb = $this->createQueryBuilder('p');
          foreach ($fields as $field) {
              if (isset($sorting[$field])) {
                  $direction = ($sorting[$field] === 'asc') ? 'asc' : 'desc';
                  $qb->addOrderBy('p.'.$field, $direction);
              }
          }
          $qb->setMaxResults($limit) ;
          $qb->setFirstResult($limit * ($page-1)) ;
          $query = $qb->getQuery() ;
          $paginator = new \Doctrine\ORM\Tools\Pagination\Paginator($query);
          $this->totalRows = count($paginator);
          //return  $query->execute() ;
          return  $query->getArrayResult(); ;
      }



}
